//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamJaxConsoleGame.Lib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameScreenResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameScreenResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamJaxConsoleGame.Lib.Resources.GameScreenResources", typeof(GameScreenResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your abilities:.
        /// </summary>
        internal static string AbilitiesDescription {
            get {
                return ResourceManager.GetString("AbilitiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *===========================================*.
        /// </summary>
        internal static string BreakRow {
            get {
                return ResourceManager.GetString("BreakRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose hero&apos;s class.
        /// </summary>
        internal static string ClassChoice {
            get {
                return ResourceManager.GetString("ClassChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your inventory.
        /// </summary>
        internal static string InventoryDescription {
            get {
                return ResourceManager.GetString("InventoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your items:.
        /// </summary>
        internal static string ItemsDesciption {
            get {
                return ResourceManager.GetString("ItemsDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your hero&apos;s name.
        /// </summary>
        internal static string LoadHearoCreation {
            get {
                return ResourceManager.GetString("LoadHearoCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose hero&apos;s race.
        /// </summary>
        internal static string RaceChoice {
            get {
                return ResourceManager.GetString("RaceChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your skills:.
        /// </summary>
        internal static string SkillsDescription {
            get {
                return ResourceManager.GetString("SkillsDescription", resourceCulture);
            }
        }
    }
}
